---
version: "3.9"
services:

  node-15:
    image: docker.pkg.github.com/valorad/va-docka/code-server-node:v15-v3
    container_name: code-server-node-15
    restart: always
    environment:
      - EXEC_USER_ID=1002  # (optional) Your new user ID if needed. This image already has 1 normal user.
      - EXEC_USER_NAME=node2 # (optional) Your new user name if needed.
      - EXEC_PASSWD=my-password-for-new-user # (optional) Your new user password.
    volumes:
      - /workspace/www/code-server/config.yaml:/etc/codeServer/config.yaml # Path to code-server config file if you are overriding
      - /workspace/www/code-server/node/15:/workspace/www/code-server # Path to where you store code-server user data (including settings.json) and extensions.
      - /workspace/workbench:/workspace/workbench # Path to your code that you will edit
    networks:
      - main

  dotnet-5:
    image: docker.pkg.github.com/valorad/va-docka/code-server-dotnet:v5-v3
    container_name: code-server-dotnet-5
    restart: always
    environment:
      - EXEC_USER_ID=2000  # (optional) Your new user ID if needed. This image already has 1 normal user.
      - EXEC_USER_NAME=dotnet2000 # (optional) Your new user name if needed.
      - EXEC_PASSWD=my-password-for-new-user # (optional) Your new user password.
    volumes:
      - /workspace/www/code-server/config.yaml:/etc/codeServer/config.yaml # Path to code-server config file if you are overriding
      - /workspace/www/code-server/dotnet/5:/workspace/www/code-server # Path to where you store code-server user data (including settings.json) and extensions.
      - /workspace/workbench:/workspace/workbench # Path to your code that you will edit
    networks:
      - main

networks:
  main:
    external:
      name: main