FROM node:current-buster-slim

ARG SV_CONFIG_DIR=/etc/codeServer
ARG BASE_DIR=/workspace/www/code-server


COPY common/config.yaml ${SV_CONFIG_DIR}/
COPY common/settings.json ${BASE_DIR}/User/
COPY common/entry-sudo.sh /boot/entry.sh

ENV EXEC_PASSWD=please_change

WORKDIR ${BASE_DIR}/

# Install code-server
RUN apt update \
    && apt install -y sudo curl git \
    && curl -fsSL https://code-server.dev/install.sh | sh \
    && apt clean

# Install needed extensions
RUN code-server --config ${SV_CONFIG_DIR}/config.yaml \
    --install-extension=pkief.material-icon-theme

# Make sure normal user can write code-server directory if that directory isn't mounted by a volume
RUN chmod 777 -R ${BASE_DIR}/

# The base image already has a normal user, making him eligible for going sudo
RUN username=$(id -nu 1000) \
    && echo "$username:$EXEC_PASSWD" | chpasswd \
    && usermod -aG sudo $username

VOLUME ${BASE_DIR}
EXPOSE 8848

ENTRYPOINT ["/boot/entry.sh"]
CMD ["code-server", "--config", "/etc/codeServer/config.yaml"]
