FROM debian:11-slim

ARG BASE_DIR=/workspace/www/mega-cmd
ARG DEB_NAME=megacmd_1.5.1-1.1_amd64.deb

WORKDIR ${BASE_DIR}/

RUN apt update \
    && apt install -y wget \
    && wget https://mega.nz/linux/MEGAsync/Debian_11/amd64/${DEB_NAME} \
    && apt install -y ./${DEB_NAME} \
    && rm ./${DEB_NAME} \
    && apt clean

RUN useradd -m -s /bin/bash -G sudo -u 1000 mega

CMD ["mega-cmd-server"]
