FROM debian:10-slim

ARG BASE_DIR=/workspace/www/mega-cmd

WORKDIR ${BASE_DIR}/

RUN apt update \
    && apt install -y wget \
    && wget https://mega.nz/linux/MEGAsync/Debian_10.0/amd64/megacmd_1.4.0-3.1_amd64.deb \
    && apt install -y ./megacmd_1.4.0-3.1_amd64.deb \
    && rm ./megacmd_1.4.0-3.1_amd64.deb \
    && apt clean

CMD ["mega-cmd-server"]
