---
services:

  main:
    image: ghcr.io/valorad/mega-cmd:latest
    restart: unless-stopped
    user: "1001:1000" # Note: DO NOT run as Root. Otherwise, the permission of sync folders will be messed up.
    volumes:
      - /sync/folder/1:/sync/folder/1
      - /sync/folder/2:/sync/folder/2
    networks:
      - main

# Remember to create this docker network manually!
networks:
  main:
    external:
      name: main
