---
version: "3.9"
services:

  latest:
    image: ghcr.io/valorad/mega-cmd:latest
    restart: always
    user: "1000"
    volumes:
      - /sync/folder/1:/sync/folder/1
      - /sync/folder/2:/sync/folder/2
    networks:
      - main

# Remember to create this docker network manually!
networks:
  main:
    external:
      name: main
