FROM scratch

ENV container docker

ADD ./dist/arch-rootfs-2018.02.22.tar.xz /

ADD ./shell.sh /workspace/

# systemd inside a container
VOLUME [ "/sys/fs/cgroup" ]

VOLUME [ "/workspace/workbench" ]
VOLUME [ "/workspace/docking" ]

WORKDIR /workspace/workbench

CMD ["/bin/bash"]