FROM archlinux/base

ENV container docker
ENV init /lib/systemd/systemd

## Software Installation
RUN pacman -Syu --noconfirm \ 
 && pacman -S sudo --noconfirm \
 && pacman -Scc --noconfirm
# systemd setup
# --> clean uneeded services
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
      rm -f /lib/systemd/system/multi-user.target.wants/*;\
      rm -f /etc/systemd/system/*.wants/*;\
      rm -f /lib/systemd/system/local-fs.target.wants/*; \
      rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
      rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
      rm -f /lib/systemd/system/basic.target.wants/*;\
      rm -f /lib/systemd/system/anaconda.target.wants/*; \
      systemctl set-default multi-user.target;

# systemd inside a container
VOLUME [ "/sys/fs/cgroup" ]

VOLUME [ "/workspace/workbench" ]
VOLUME [ "/workspace/docking" ]

ADD ./shell.sh /workspace/

WORKDIR /workspace/workbench

ENTRYPOINT ["/workspace/shell.sh"]