# ============================================================
FROM golang:1.23-alpine3.21 as builder

WORKDIR /src

RUN set -x && \
	apk --no-cache add git gcc libc-dev make

RUN git clone https://github.com/cloudflare/cfssl.git /src && \
    git clone https://github.com/cloudflare/cfssl_trust.git /etc/cfssl && \
    make clean && \
    make all

# ============================================================
FROM alpine:3.21 as runner

ARG BASE_DIR=/workspace/www/cfssl

WORKDIR ${BASE_DIR}/

COPY --from=builder /etc/cfssl /etc/cfssl
COPY --from=builder /src/bin/ /usr/bin

EXPOSE 8888

CMD [ \
    "cfssl", \
    "serve", \
    "-address=0.0.0.0", \
    "-port=8888", \
    "-ca=/workspace/www/cfssl/configs/_activeCA/cert.pem", \
    "-ca-key=/workspace/www/cfssl/configs/_activeCA/key.pem", \
    "-config=/workspace/www/cfssl/configs/_activeCA/config.json", \
    "-db-config=/workspace/www/cfssl/configs/db.json" \
]
