## example to build and run
# docker build . -t fedora-nonroot

FROM fedora

## Software Installation

# enable RPM Fusion
RUN dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
 && dnf update -y \ 
 && dnf install -y sudo \
 && rm -rf /var/cache/dnf/* \
 && rm -rf /var/cache/yum/*

VOLUME [ "/workspace/workbench" ]
VOLUME [ "/workspace/docking" ]

ADD ./index.sh /workspace/

WORKDIR /workspace/workbench

ENTRYPOINT ["/workspace/index.sh"]